title: "My Portfolio"
description: "Personal portfolio website showcasing projects and work."
baseurl: "" # Leave empty unless the site is in a subdirectory
url: "https://kimiafazeli1.github.io" # Change this to your GitHub Pages URL

# Theme and Plugins
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Navigation
navigation:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Contact"
    url: "/contact/"

# SEO and Socials
author:
  name: "Kimia Fazeli"
  email: "your-email@example.com"
  twitter: "your-twitter"
  github: "kimiafazeli1"

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"

